[functions]
  directory = "functions"

[build]
    publish = '_site'
    command = 'npm run build'

[[redirects]]
  from = "/sites/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/screenshot/*"
  to = "/.netlify/builders/screenshot"
  status = 200
  force = true